### PR TITLE
Create WiFiKilL3r-sv.ts

### PR DESCRIPTION
**Pull request by eson57**
Thanks for a useful app. :+1:

### CODE REVIEW

**Comment by theyosh** [comment]
Cool Swedish language! Thanks!

**Comment by eson57** [comment]
Here's more.  ;-)

There's a missing translation string for the notification popup message... "_WiFi is disabled due to leaving trusted network_"
Text on cover page "Last check" doesn't translate. Don't know if it's missing or a bug.

skarmbild_20161106_003

**Comment by theyosh** [comment]
Ah yesh, the notification message is from Python. So that is not being translated :-1:  I will leave that in English. Cover page is not yet translate-able. If you post the translation for 'Last check' here, I can added with another update.

**Comment by theyosh** [comment]
I have it already: Senaste kontroll

**Comment by eson57** [comment]
OK... that should be "Senaste kontroll".

**Comment by theyosh** [comment]
:+1:

**Pull request merged**
